name: ONDC:RET13
versions:
  - id: 1.2.5
    reporting: false
    supportedActions:
      $ref: "src/config/RET13/V-1.2.5/supportedActions/index.yaml"
    usecase:
      - name: BPC
        flows: "./V-1.2.5/BPC/flows/index.yaml"
