name: ONDC:FIS12
versions:
  - id: 2.0.2
    reporting: false
    usecase:
      - name: GOLD LOAN
        flows: "./V-2.0.2/goldLoan/flows/index.yaml"
    supportedActions:
      $ref: "src/config/FIS12/V-2.0.2/supportedActions/index.yaml"
