domain:
  - name: ONDC:TRV11
    versions:
      - id: 2.0.0
        reporting: true
        usecase:
          - name: Metro
            flows: "./TRV11/V-2.0.0/metro/flows/index.yaml"
          - name: Bus
            flows: "./TRV11/V-2.0.0/bus/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV11/V-2.0.0/supportedActions/index.yaml"
      - id: 2.0.1
        reporting: true
        usecase:
          - name: Metro
            flows: "./TRV11/V-2.0.1/metro/flows/index.yaml"
          - name: Bus
            flows: "./TRV11/V-2.0.1/bus/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV11/V-2.0.1/supportedActions/index.yaml"
  - name: ONDC:TRV12
    versions:
      - id: 2.0.0
        reporting: false
        usecase:
          - name: Airline
            flows: "./TRV12/V-2.0.0/airline/flows/index.yaml"
          - name: Intercity
            flows: "./TRV12/V-2.0.0/intercity/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV12/V-2.0.0/supportedActions/index.yaml"   
usecases:
  domain:
    - key: ONDC:TRV11
      version:
        - key: 2.0.0
          usecase:
            - Metro
            - Bus
        - key: 2.0.1
          usecase:
            - Metro
            - Bus
    - key: ONDC:TRV12
      version:
        - key: 2.0.0
          usecase:
            - Intercity       
            - Airline              
 