flows: 
  - id: Gold_Loan_Without_Account_Aggregator
    description: Gold Loan without Account Aggregator - Selection and approval flow
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code (PAN India "*")
            type: text
            payloadField: $.context.location.city.code
      - key: on_search
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: consumer_information_form
        label: form link provided in on_select
        type: HTML_FORM
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        input:
          - name: form_submission_id
            label: Enter Form Submission id
            type: HTML_FORM
            reference: $.reference_data.consumer_information_form
      - key: select_2
        type: select
        unsolicited: false
        pair: on_select_2
        owner: BAP
        expect: false
        force_proceed: true
      - key: on_select_2
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: kyc_verification_status
        label: form link provided in on_select
        type: HTML_FORM
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        input:
          - name: form_submission_id
            label: Enter Form Submission id
            type: HTML_FORM
            reference: $.reference_data.kyc_verification_status
      - key: on_status_unsolicited
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        force_proceed: true
      - key: status
        type: status
        unsolicited: false
        pair: on_status
        owner: BAP
        expect: true
      - key: on_status
        type: on_status
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        force_proceed: true
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false

  - id: Gold_Loan_Foreclosure
    description: Gold Loan - Loan Foreclosure - Update and notification flow
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code (PAN India "*")
            type: text
            payloadField: $.context.location.city.code
      - key: on_search
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: consumer_information_form
        label: form link provided in on_select
        type: HTML_FORM
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        input:
          - name: form_submission_id
            label: Enter Form Submission id
            type: HTML_FORM
            reference: $.reference_data.consumer_information_form
      - key: select_2
        type: select
        unsolicited: false
        pair: on_select_2
        owner: BAP
        expect: false
        force_proceed: true
      - key: on_select_2
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: kyc_verification_status
        label: form link provided in on_select
        type: HTML_FORM
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        input:
          - name: form_submission_id
            label: Enter Form Submission id
            type: HTML_FORM
            reference: $.reference_data.kyc_verification_status
      - key: on_status_unsolicited
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        force_proceed: true
      - key: status
        type: status
        unsolicited: false
        pair: on_status
        owner: BAP
        expect: true
      - key: on_status
        type: on_status
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        force_proceed: true
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: update
        type: update
        unsolicited: false
        pair: on_update
        owner: BAP
        expect: true
      - key: on_update
        type: on_update
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: on_update_unsolicited
        type: on_update
        unsolicited: true
        pair: null
        owner: BPP
        expect: false      

  - id: Gold_Loan_Missed_EMI
    description: Gold Loan - Missed-EMI Payment - Update and notification flow
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code (PAN India "*")
            type: text
            payloadField: $.context.location.city.code
      - key: on_search
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: consumer_information_form
        label: form link provided in on_select
        type: HTML_FORM
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        input:
          - name: form_submission_id
            label: Enter Form Submission id
            type: HTML_FORM
            reference: $.reference_data.consumer_information_form
      - key: select_2
        type: select
        unsolicited: false
        pair: on_select_2
        owner: BAP
        expect: false
        force_proceed: true
      - key: on_select_2
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: kyc_verification_status
        label: form link provided in on_select
        type: HTML_FORM
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        input:
          - name: form_submission_id
            label: Enter Form Submission id
            type: HTML_FORM
            reference: $.reference_data.kyc_verification_status
      - key: on_status_unsolicited
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        force_proceed: true
      - key: status
        type: status
        unsolicited: false
        pair: on_status
        owner: BAP
        expect: true
      - key: on_status
        type: on_status
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        force_proceed: true
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: update
        type: update
        unsolicited: false
        pair: on_update
        owner: BAP
        expect: true
      - key: on_update
        type: on_update
        unsolicited: false
        pair: null
        owner: BPP
        expect: false

      - key: on_update_unsolicited
        type: on_update
        unsolicited: true
        pair: null
        owner: BPP
        expect: false

  - id: Gold_Loan_Pre_Part_Payment
    description: Gold Loan - Pre-Part Payment - Update and notification flow
    sequence:
      - key: search
        type: search
        unsolicited: false
        pair: on_search
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code (PAN India "*")
            type: text
            payloadField: $.context.location.city.code
      - key: on_search
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: consumer_information_form
        label: form link provided in on_select
        type: HTML_FORM
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        input:
          - name: form_submission_id
            label: Enter Form Submission id
            type: HTML_FORM
            reference: $.reference_data.consumer_information_form
      - key: select_2
        type: select
        unsolicited: false
        pair: on_select_2
        owner: BAP
        expect: false
        force_proceed: true
      - key: on_select_2
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: kyc_verification_status
        label: form link provided in on_select
        type: HTML_FORM
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
        input:
          - name: form_submission_id
            label: Enter Form Submission id
            type: HTML_FORM
            reference: $.reference_data.kyc_verification_status        
      - key: on_status_unsolicited
        type: on_status
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
        force_proceed: true
      - key: status
        type: status
        unsolicited: false
        pair: on_status
        owner: BAP
        expect: true
      - key: on_status
        type: on_status
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: init
        type: init
        unsolicited: false
        pair: on_init
        owner: BAP
        expect: false
        force_proceed: true
      - key: on_init
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: confirm
        type: confirm
        unsolicited: false
        pair: on_confirm
        owner: BAP
        expect: false
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: update
        type: update
        unsolicited: false
        pair: on_update
        owner: BAP
        expect: true
      - key: on_update
        type: on_update
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: on_update_unsolicited
        type: on_update
        unsolicited: true
        pair: null
        owner: BPP
        expect: false